### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by adrianbgo** [adrianbgo/adrianbgo.github.io#3]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
A button component

## Task List
- [x] Crete a rounded button component
- [x] Filled and Hollow color options
- [ ] Sliding variant
- [ ] Should have a gradient high to low that adjusts on hover
