### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by adrianbgo** [adrianbgo/adrianbgo.github.io#4]
# Create an Info Card Component

## Task List
- [ ] Image or Icon
- [ ] Heading
- [ ] Body text
- [ ] Border
- [ ] Slight cornered gradient
- [ ] Glassmorphic
- [ ] Movement on hover
